// Generated by Ignite ignite.com/cli
import { Registry } from '@cosmjs/proto-signing'
import { IgniteClient } from "./client";
import { MissingWalletError } from "./helpers";
import { IgntModule as VnicVnicV_1, msgTypes as VnicVnicV_1MsgTypes } from './vnic/vnic/v1'


const Client = IgniteClient.plugin([
    VnicVnicV_1
]);

const registry = new Registry([
  ...VnicVnicV_1MsgTypes,
  
])

export {
    Client,
    registry,
    MissingWalletError
}
